### ISSUE TITLE
mg.iter_graph() is strangely absent from reference docs

### ISSUE THREAD

**Issue by shakfu** [ronaldoussoren/modulegraph2#24]
I just wanted to highlight that the ability to iterate over the graph should be more prominent in the reference docs, since it is such a typical use case.

In fact, I thought, this would come intuitively:

```python
mg = modulegraph2.ModuleGraph()
mg.add_module('test_import')
for I in mg:
    print(i)
```
but got a `TypeError: 'ModuleGraph' object is not iterable`

Then looking how `.report()` was implemented highlighted the use of `.iter_graph()` which is part of your `objectgraph` api.

Anyway, no biggie, just want to ask you to include an iteration example in the reference docs to prevent future confusion.

**Comment by ronaldoussoren** [comment]
I've added a graph iteration example in d7921e4.  Note that documentation already mentions that the graph is a subclass of ``objectgraph.ObjectGraph``

**Comment by shakfu** [comment]
@ronaldoussoren Thanks!
